name: Project Continuous Integration (CI) Continuous Deployment (CD)
description: |
  This workflow runs on every push and pull request to the main branch.
  It sets up a Python environment, installs dependencies, runs linting,
  type checking, and tests for the project.

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install core dependencies
        run: |
          pip install --upgrade "pip<24.1"
          pip install -r requirements-core.txt

      - name: Install LLM dependencies
        run: |
          pip install -r requirements-llm.txt

      - name: Lint
        run: |
          flake8 src/

      - name: Type Check
        run: |
          mypy src/

      - name: Run Tests
        run: |
          pytest --cov=src
